version: 2.1

description: |
  Build a Nginx AMI
display:
  home_url: https://github.com/superbounou/livestorm_app

executors:
  default:
    description: |
      The HashiCorp provided Packer container
    parameters:
      packer-version:
        type: string
        default: 1.5.1
    docker:
      - image: hashicorp/packer:1.6.0

commands:
  validate:
    description: "Run a validate on a Packer template"
    parameters:
      template:
        description: |
         nginx AMI template
        type: string
        default: nginx.json
      args:
        description: |
          Arguments to pass to the packer build command
        type: string
        default: ""

    steps:
      - run:
          name: "Run a packer validate"
          command: packer validate << parameters.template >>

validate:
  packer:
    description: Run a packer validate
    usage:
      version: 2.1

      orbs:
        packer: salaxander/packer@0.1

      jobs:
        packer-nginx:
          executor: packer/default
          steps:
            - checkout
            - build:
                template: nginx.json

      workflows:
        version: 2
        packer:
          jobs:
            - validate