version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/packer:1.6.0
    steps:
      - checkout
      - run:
          name: Validate base
          command: packer validate nginx.json
  build-base:
    docker:
      - image: hashicorp/packer:1.6.0
    working_directory: ~/packer
    steps:
      - checkout
      - attach_workspace:
          at: ~/packer
      - run:
          name: Build base
          command: packer build nginx.json
          no_output_timeout: 30m
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate
      - build-base:
          requires:
            - validate
      